variables:
  APP_NAME: api-rest
  ARTIFACT_NAME: api-rest.zip

image: golang:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/application
  artifacts:
    paths:
      - $ARTIFACT_NAME
test:
  stage: test
  script:
    - go test -v ./...

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region us-east-1
    - eb create api-rest-dev
    - eb deploy api-rest-dev
