variables:
  APP_NAME: api-rest
  ENVIRONMENT_NAME: api-rest-dev

image: golang:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
  - apt-get update && apt-get install -y python3-pip
  - pip3 install --upgrade --user awsebcli
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/application
    - eb init -p "go-1.9" $APP_NAME --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
    - eb create $ENVIRONMENT_NAME --single
  artifacts:
    paths:
      - build/
test:
  stage: test
  script:
    - go test -v ./...

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip install --upgrade --user awsebcli
    - eb init -p "python-3.7" $APP_NAME --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
    - eb use $ENVIRONMENT_NAME
    - eb deploy
