variables:
  APP_NAME: api-rest
  ARTIFACT_NAME: api-rest-v$CI_PIPELINE_IID.zip

image: golang:latest


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - apt-get update && apt-get install -y zip
    - go build -o $APP_NAME cmd/main/main.go
    - zip -r $ARTIFACT_NAME $APP_NAME
  artifacts:
    paths:
      - $ARTIFACT_NAME
test:
  stage: test
  script:
    - go test -v ./...

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region us-east-1
    - aws s3 cp $ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
    - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$S3_BUCKET,S3Key=$ARTIFACT_NAME
    - aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name production --version-label $CI_PIPELINE_IID

