variables:
  APP_NAME: application
  ARTIFACT_NAME: api-rest

image: golang:latest


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    # - apt-get update && apt-get install -y zip
    - GOOS=linux GOARCH=amd64 go build -o bin/$APP_NAME cmd/main/main.go
    # - zip -r $ARTIFACT_NAME $APP_NAME
  artifacts:
    paths:
      # - $ARTIFACT_NAME
     - bin/$APP_NAME
test:
  stage: test
  script:
    - go test -v ./...

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region us-east-1
    - aws s3 cp bin/$APP_NAME s3://$S3_BUCKET/$ARTIFACT_NAME/bin/$APP_NAME
    - aws elasticbeanstalk create-application-version --application-name $ARTIFACT_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$S3_BUCKET,S3Key=$ARTIFACT_NAME/bin/$APP_NAME
    - aws elasticbeanstalk update-environment --application-name $ARTIFACT_NAME --environment-name production --version-label $CI_PIPELINE_IID

