image: golang:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - go build -o api-rest cmd/main/main.go
  artifacts:
    paths:
      - api-rest

test:
  stage: test
  script:
    - go test -v ./...

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region us-east-1
    - aws s3 cp api-rest s3://$S3_BUCKET/api-rest
    - aws elasticbeanstalk update-environment --environment-name production --version-label $S3_BUCKET/api-rest
  only:
    - main
  dependencies:
  - build
